import Head from 'next/head'
import Nav from './components/Nav'
import Hero from './components/Hero'
import Posts from './components/Posts'
import Infographic from './components/Infographic'
import Gallery from './components/Gallery'
import Footer from './components/Footer'
import CaseStudies from './components/CaseStudies'

export default function Home() {
  return (
    <>
      <Head>
        <title>Motive Technical Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Nav />
      </header>
      <main>
        <Hero />
        <Posts />
        <Infographic />
        <CaseStudies />
        <Gallery />
      </main>
      <footer>
        <Footer/>
      </footer>
    </>
  )
}
